# Generated by Django 5.1.12 on 2025-10-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
