# Generated by Django 5.1.12 on 2025-10-02 13:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_service_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Atribuição",
                "verbose_name_plural": "Atribuições",
            },
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Auditoria",
                "verbose_name_plural": "Auditorias",
            },
        ),
        migrations.AlterModelOptions(
            name="availability",
            options={
                "verbose_name": "Disponibilidade",
                "verbose_name_plural": "Disponibilidades",
            },
        ),
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ["name"],
                "verbose_name": "Membro",
                "verbose_name_plural": "Membros",
            },
        ),
        migrations.AlterModelOptions(
            name="schedulemonth",
            options={
                "ordering": ["-year", "-month"],
                "verbose_name": "Escala Mensal",
                "verbose_name_plural": "Escalas Mensais",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["date", "time"],
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
        migrations.AlterUniqueTogether(
            name="assignment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="schedulemonth",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmado"),
                    ("suggested", "Sugerido"),
                    ("replaced", "Substituído"),
                ],
                db_index=True,
                default="suggested",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="table",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="availability",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="scheduling.member",
            ),
        ),
        migrations.AlterField(
            model_name="availability",
            name="shift",
            field=models.CharField(
                choices=[("morning", "Manhã"), ("evening", "Noite")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="availability",
            name="weekday",
            field=models.IntegerField(
                db_index=True,
                help_text="0=Seg ... 6=Domingo",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="last_served_at",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="monthly_limit",
            field=models.PositiveIntegerField(
                default=2, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="schedulemonth",
            name="month",
            field=models.PositiveIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="schedulemonth",
            name="year",
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="time",
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(
                choices=[("Culto", "Culto"), ("Extra", "Extra")],
                db_index=True,
                default="Culto",
                max_length=12,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="auditlog",
            unique_together={("table", "record_id", "created_at")},
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["service", "status"], name="assignment_service_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["member", "status"], name="assignment_member_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["status", "created_at"], name="assignment_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["table", "created_at"], name="audit_table_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "created_at"], name="audit_action_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="availability",
            index=models.Index(
                fields=["member", "active"], name="availability_member_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="availability",
            index=models.Index(
                fields=["weekday", "shift", "active"], name="availability_wsa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["active"], name="member_active_idx"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["last_served_at"], name="member_last_served_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedulemonth",
            index=models.Index(
                fields=["year", "month"], name="schedule_year_month_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["date", "time"], name="service_date_time_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["type", "date"], name="service_type_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("service", "member"), name="uniq_assignment_service_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.UniqueConstraint(
                fields=("member", "weekday", "shift"),
                name="uniq_availability_member_day_shift",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulemonth",
            constraint=models.UniqueConstraint(
                fields=("year", "month"), name="uniq_schedule_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("date", "time"), name="uniq_service_date_time"
            ),
        ),
    ]
